### ISSUE TITLE
ghosts discards lines containing valid domains with an underscore

### ISSUE THREAD

**Issue by llacb47** [StevenBlack/ghosts#10]
Steps to reproduce:

1. create a text file named `test.txt` with content:
```
0.0.0.0 example123.com
0.0.0.0 tesla.com
0.0.0.0 ogs.google.com.hk
0.0.0.0 fb_servpub-a.akamaihd.net
0.0.0.0 client_monitor.isnssdk.com
0.0.0.0 www.zappos.com
```

2. run ghosts with `$ go run ./ghosts -m ./test.txt -o -s > testsorted.txt`

expected content of `testsorted.txt`:
```
0.0.0.0 fb_servpub-a.akamaihd.net
0.0.0.0 ogs.google.com.hk
0.0.0.0 example123.com
0.0.0.0 client_monitor.isnssdk.com
0.0.0.0 tesla.com
0.0.0.0 www.zappos.com
```

actual content:
```
0.0.0.0 ogs.google.com.hk
0.0.0.0 example123.com
0.0.0.0 tesla.com
0.0.0.0 www.zappos.com
```

**Comment by StevenBlack** [comment]
Hi LE @llacb47.

[This monster regex](https://github.com/StevenBlack/ghosts/blob/master/main.go#L115) needs work.  That's a bug!

**Comment by StevenBlack** [comment]
Thanks LE!  This is now fixed.  Creating a new release shortly.
