### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by m040601** [StevenBlack/ghosts#11]
Hi Steve, thank you for your amazing and **very usefull work** on the hosts lists and tools. You have a typo in:

```
**## Related repositories

* [StevenBlack/hosts](https://github.com/StevenBlack/hosts) is my amalgamated hosts file, with custom variants, from various curated sources.
* [StevenBlack/rhosts](https://github.com/StevenBlack/ghosts) hosts tools, written in Rust, just getting started on that.**
```

Should be,

`[StevenBlack/rhosts](https://github.com/StevenBlack/`**_rhosts_**`)`

Looking forward to the Rust thingy.

**Comment by StevenBlack** [comment]
Thank you @m040601, good catch!  Fixed.

Closing.
