### ISSUE TITLE
Add/keep the traditional top-section of hosts file

### ISSUE THREAD

**Issue by StevenBlack** [StevenBlack/ghosts#6]
If we're outputting a hosts file with IP addresses, then we want to also include, at the top,

```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

... or something terse but reasonable.

**Comment by ikonia** [comment]
I'd request you don't keep this, this isn't in my view in scope of what you're doing, the host file is managed by the the system owners, and the loop back interfaces can be used and have aliases associated with them. Provide the data for the blocking/blacklisting and make it the system owners problem to integrate them into their system eg: hostfile, application config, dns zone file as hard coding this could impact peoples systems

**Comment by StevenBlack** [comment]
I think you’ve got a good take here, Matt @ikonia.

But if this tool combines, sorts, and otherwise mangles input source hosts lists, I’d like to ensure the basic elements stay at the top, and aren’t subsumed.

Commits from just a few minutes ago preserve the file header.  Something like that, but for the common names for those interfaces.  While preserving their setting.

**Comment by ikonia** [comment]
right, it manages input source lists, not the hostfile itself, if you can ensure they are present but don't overlap/duplicate/manipulate the existing entries in the hostfile that is the perfect solution, the risk I'm worried about is any user or application defined entries in the hostfile get broken.

My honest view is that you should manage and provide the data, and let the user manage the hostfile itself more so if you're ensuring things like IPv6 entries are in, somesystems will have IPv6 disabled for security reasons, putting the loop back interface in to respond to IPV6 can open a risk door partially ?

it's just my opinion, and food for though.

**Comment by StevenBlack** [comment]
Matt @ikonia I’m just checking... it sounds like you’re referring to the `hosts` repo?  This is `ghosts`, a specialized tool for task-specific transformation and comparison, written in Go.

**Comment by ikonia** [comment]
didn't think this was the host repo, but I may have miss-understood the function of ghosts, I thought ghosts was to manipulate and build "lists" or files from multiple data sources and have capabilities such as search/diff/format etc etc, so I'm aware it's for ghost (as I'm keen to try it myself as it may fix my personal DNS conversion overhead) but I may have not fully grasped the use case, reading the udpated readme's makes it a little clearer to me.
